name: Tests
on: push

jobs:
  pytest:
    runs-on: ubuntu-latest

    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install uv with cache
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.2"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install nox
        uses: wntrblm/nox@2025.02.09

      - run: nox